require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/post_levels", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PostLevel. As you add validations to PostLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PostLevel.create! valid_attributes
      get post_levels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      post_level = PostLevel.create! valid_attributes
      get post_level_url(post_level)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_post_level_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      post_level = PostLevel.create! valid_attributes
      get edit_post_level_url(post_level)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PostLevel" do
        expect {
          post post_levels_url, params: { post_level: valid_attributes }
        }.to change(PostLevel, :count).by(1)
      end

      it "redirects to the created post_level" do
        post post_levels_url, params: { post_level: valid_attributes }
        expect(response).to redirect_to(post_level_url(PostLevel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PostLevel" do
        expect {
          post post_levels_url, params: { post_level: invalid_attributes }
        }.to change(PostLevel, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post post_levels_url, params: { post_level: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested post_level" do
        post_level = PostLevel.create! valid_attributes
        patch post_level_url(post_level), params: { post_level: new_attributes }
        post_level.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the post_level" do
        post_level = PostLevel.create! valid_attributes
        patch post_level_url(post_level), params: { post_level: new_attributes }
        post_level.reload
        expect(response).to redirect_to(post_level_url(post_level))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        post_level = PostLevel.create! valid_attributes
        patch post_level_url(post_level), params: { post_level: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested post_level" do
      post_level = PostLevel.create! valid_attributes
      expect {
        delete post_level_url(post_level)
      }.to change(PostLevel, :count).by(-1)
    end

    it "redirects to the post_levels list" do
      post_level = PostLevel.create! valid_attributes
      delete post_level_url(post_level)
      expect(response).to redirect_to(post_levels_url)
    end
  end
end
